trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: prueba-tecnica

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self
      displayName: 'Cloning the repository'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        python -m unittest discover -s tests
      displayName: 'Run unit tests'

    - script: |
        pip install pylint
        pylint app.py
      displayName: 'Run static code analysis'

    - script: |
        pip install bandit
        bandit -r app.py
      displayName: 'Run vulnerability scan'

    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
      displayName: 'Build and push Docker image'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'aks-service-connections'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'deployment.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
      displayName: 'Deploy app'

- stage: Notify
  jobs:
  - job: Notify
    steps:
    - script: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Build and deployment completed successfully."}' $(slackWebhookUrl)
      displayName: 'Send Slack notification'
