trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: prueba-tecnica

stages:
- stage: Tests
  jobs:
  - job: RunTests
    steps:
    - checkout: self
      displayName: 'Cloning the repository'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
      displayName: 'Upgrade pip'
      
    - script: |
        python -m unittest discover -s tests
      displayName: 'Run unit tests'

    - script: |
        pip install pylint
        pylint app.py || true
      displayName: 'Run static code analysis'

    - script: |
        pip install bandit
        bandit -r app.py
      displayName: 'Run vulnerability scan'

- stage: Build
  dependsOn: Tests
  jobs:
  - job: BuildImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dcr-service-connetions'
        repository: 'prueba_tecnica'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
      displayName: 'Build and push Docker image'

# - stage: Deploy
#   dependsOn: Build
#   jobs:
#   - job: DeployToK8s
#     steps:
#     - task: Kubernetes@1
#       inputs:
#         connectionType: 'Kubernetes Service Connection'
#         kubernetesServiceEndpoint: 'aks-service-connections'
#         namespace: 'default'
#         command: 'apply'
#         useConfigurationFile: true
#         configuration: 'deployment.yaml'
#         secretType: 'dockerRegistry'
#         containerRegistryType: 'Azure Container Registry'
#       displayName: 'Deploy app'

- stage: Notify
  # dependsOn: Deploy
  jobs:
  - job: NotifySlack
    steps:
    - script: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Build and deployment completed successfully."}' $(slackWebhookUrl)
      displayName: 'Send Slack notification'
